server:
  port: 8090
spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: u5750599680@gmail.com
    password: pmcf ljuq utep xpbq
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


app:
  mail:
    enabled: false