spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    validateMigrationNaming: true

logging:
  level:
    org:
      flyway=DEBUG:

jwt:
  secret: "YOUR_LONG_SECRET_KEY_AT_LEAST_32_BYTES"
  expiration: 36000000
